# This is a basic workflow to help you get started with Actions

name: IaC Postgres

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: ["terraform/**"]
  workflow_dispatch:

jobs:
  terraform-aws:
    name: "Terraform AWS RDS"
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          
      - name: Create S3 Bucket
        run: aws s3 mb s3://${{ secrets.AWS_BUCKET_NAME }}
  
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Terraform init
        working-directory: ./src
        run: terraform init -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}"

      - name: Terraform Apply 
        working-directory: ./src
        run: terraform apply --auto-approve
