name: AWS Pre Requirements

on:
  workflow_call:
    inputs:
      AWS_BUCKET_NAME:
        required: true
        type: string
      AWS_TABLE_NAME:
        required: true
        type: string
      workflow_dispatch:

jobs:
  pre-reqs-terraform-aws:
    name: "AWS Pre Requirements"
    runs-on: ubuntu-latest
    steps:
      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Validate DynamoDB Table
        run: aws dynamodb list-tables | grep -iq "${{ inputs.AWS_TABLE_NAME }}"
        id: validate_table
      
      - name: Create Dynamodb table
        if: steps.validate_table.outputs.exit-code == 1
        #if: steps.validate_table.outputs['time'] == ''
        run: aws dynamodb create-table --table-name ${{ inputs.AWS_TABLE_NAME }} --attribute-definitions AttributeName=LockID,AttributeType=S --key-schema AttributeName=LockID,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
        continue-on-error: true

      - name: Validate S3 Bucket
        run: aws s3 ls | grep -iq "${{ inputs.AWS_BUCKET_NAME }}"
        id: validate_bucket
      
      - name: Create S3 Bucket
        #if: steps.validate_bucket.outputs['time'] == ''
        if: steps.validate_bucket.outputs.exit-code == 1
        run: aws s3 mb s3://${{ inputs.AWS_BUCKET_NAME }}
        continue-on-error: true
