name: IaC Mongo DB

on:
  workflow_call:
  #workflow_run:
  #  workflows: ["AWS Pre Requirements"]
  
  push:
    branches: [ "github-alancarvalho-patch-2" ]
    #paths: ["terraform/**"]
    #paths: ["terraform/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["terraform/**"]
  workflow_dispatch:

jobs: 
  call-workflow-aws-pre-requirements:
    uses: ./.github/workflows/aws-pre-requirements.yml
    secrets: inherit
    with:
      AWS_BUCKET_NAME  : s3-terraform-mongodb
      AWS_TABLE_NAME: terraform-mongodb-lock
   
  create-mongo-database:
    needs: call-workflow-aws-pre-requirements
    name: "Create MongoDB database"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      
      - name: Terraform Init
        run: |
          cd terraform/mongo && terraform init \
            -backend-config="bucket=s3-terraform-mongodb" \
            -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=terraform-mongodb-lock"

      - name: Terraform Apply 
        working-directory: ./terraform/mongo
        #run: terraform apply --auto-approve -var=MONGO_DB_ORG_ID=${{ secrets.MONGO_DB_ORG_ID }} -var=MONGO_DB_PUBLIC_KEY=${{ secrets.MONGO_DB_PUBLIC_KEY }} -var=MONGO_DB_PRIVATE_KEY=${{ secrets.MONGO_DB_PRIVATE_KEY }} -var=MONGO_DB_USER=${{ secrets.MONGO_DB_USER }} -var=MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}
        run: terraform apply --auto-approve -var=MONGO_DB_ORG_ID=${{ secrets.MONGO_DB_ORG_ID }} -var=MONGO_DB_PUBLIC_KEY=${{ secrets.MONGO_DB_PUBLIC_KEY }} -var=MONGO_DB_PRIVATE_KEY=${{ secrets.MONGO_DB_PRIVATE_KEY }} -var=MONGO_DB_USER=${{ secrets.MONGO_DB_USER }} -var=MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}

        
