name: IaC Mongo DB

on:
  workflow_call: 
  push:
    branches: [ "github-alancarvalho-patch-2" ]
    #paths: ["terraform/**"]
    #paths: ["terraform/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["terraform/**"]
  workflow_dispatch:

jobs: 
  call-workflow-aws-pre-requirements:
    uses: ./.github/workflows/aws-pre-requirements.yml
    secrets: inherit
    #secrets:
      #AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESS_KEY_ID  }}
      #AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
      #AWS_SESSION_TOKEN : ${{ secrets.AWS_SESSION_TOKEN  }}
    with:
      AWS_BUCKET_NAME  : terraform-postgres
     
  create-rds-postgres-database:
    needs: call-workflow-aws-pre-requirements
    name: "Create RDS Postgres database"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      
      - name: Terraform Init
        run: |
          cd terraform && terraform init \
            -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" \
            -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=terraform-postgres-lock"

      - name: Terraform Apply 
        working-directory: ./terraform
        run: terraform apply --auto-approve -var=db_password=${{ secrets.MONGO_DB_PASSWORD }}

        
