# This is a basic workflow to help you get started with Actions

name: IaC Mongo DB

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: ["terraform/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["terraform/**"]
  workflow_dispatch:

jobs:
  terraform:
    name: "Terraform DB apply"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Terraform Mongo init
        working-directory: ./terraform/mongo
        run: terraform init

      - name: Terraform plan
        working-directory: ./terraform/mongo
        run: terraform plan -out=terraform.plan -var=MONGO_DB_ORG_ID=${{ secrets.MONGO_DB_ORG_ID }} -var=MONGO_DB_PUBLIC_KEY=${{ secrets.MONGO_DB_PUBLIC_KEY }} -var=MONGO_DB_PRIVATE_KEY=${{ secrets.MONGO_DB_PRIVATE_KEY }} -var=MONGO_DB_USER=${{ secrets.MONGO_DB_USER }} -var=MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}
        
      - name: Upload Terraform plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: terraform.plan

      #- name: Terraform Apply 
        #working-directory: ./terraform/mongo
        #run: terraform apply --auto-approve -var=MONGO_DB_ORG_ID=${{ secrets.MONGO_DB_ORG_ID }} -var=MONGO_DB_PUBLIC_KEY=${{ secrets.MONGO_DB_PUBLIC_KEY }} -var=MONGO_DB_PRIVATE_KEY=${{ secrets.MONGO_DB_PRIVATE_KEY }} -var=MONGO_DB_USER=${{ secrets.MONGO_DB_USER }} -var=MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}

      - name: Terraform Apply 
        uses: actions/checkout@v3
      - name: Download Terraform plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
      - name: Terraform apply
        run: terraform apply -auto-approve terraform.plan
        
        
