name: IaC Mongo DB

on:
  #workflow_run:
  #  workflows: ["AWS Pre Requirements"]
  push:
    branches: [ "github-alancarvalho-patch-2" ]
    #paths: ["terraform/**"]
    #paths: ["terraform/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["terraform/**"]
  workflow_dispatch:

jobs:
  pre-reqs-terraform-aws: 
    uses: fiap-architectburgers/architect-burgers-infra-base.github/workflows/aws-pre-requirements.yml@github-alancarvalho-patch-2

  create-mongo-database:
    needs: pre-reqs-terraform-aws
    name: "Create MongoDB database"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Terraform Init
        run: |
          cd terraform/mongo && terraform init \
            -backend-config="bucket=${{ secrets.AWS_BUCKET_NAME }}" \
            -backend-config="key=${{ secrets.AWS_BUCKET_FILE }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=terraform-locks"

      - name: Terraform Apply 
        working-directory: ./terraform/mongo
        run: terraform apply --auto-approve -var=MONGO_DB_ORG_ID=${{ secrets.MONGO_DB_ORG_ID }} -var=MONGO_DB_PUBLIC_KEY=${{ secrets.MONGO_DB_PUBLIC_KEY }} -var=MONGO_DB_PRIVATE_KEY=${{ secrets.MONGO_DB_PRIVATE_KEY }} -var=MONGO_DB_USER=${{ secrets.MONGO_DB_USER }} -var=MONGO_DB_PASSWORD=${{ secrets.MONGO_DB_PASSWORD }}

        
